---
title: "大法官们如何制定政策"
subtitle: "法律模型、态度模型与理性选择模型"
author: "许羽佳 石宇洋"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    self_contained: true
---
```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#93685B"
)
```
###目录

* **文献背景**

* **模型与法律模型**

* **态度模型**

* **理性选择模型**

* **模型检验**
---
class: inverse, center, middle

#文献背景
---
###作者简介

杰弗瑞·A．西格尔(Jeffrey A．segal)

* 纽约州立大学石溪分校政治学专业特聘教授，政治学系主任。

哈罗德·J．斯皮斯(Harold J.spaeth)

* 密歇根州立大学政治学系荣休教授，法学院教授。

****

###研究背景

**法律**本身是判决的**唯一标准**吗？

来自经验现实的否定。

---
class: inverse, center, middle

# 模型与法律模型
---
### 模型与法律模型

.pull-left[
**模型**

* 案例研究的缺陷

  * 外部效度的局限（External Validity）

* 模型
  
  * 复杂性的引入
  
    *  “对大量行为的最佳解释”
  
  * 对真实的**简化**
  
  * 要求：可证伪性
]
  
.pull-right[
**法律模型**

* 上启于20世纪早期**机械主义法理学**

* 基本信念：
  
  * 最高法院的裁决依据
  
   * 宪法和法律的文义、立宪者的目的、先例

* 变量：

  * 基本文义；规范视角；经验现实；
  
  * 先例；附带意见；辨析先例；
  
  * 原则限定；推翻先例
]
---
class: inverse, center, middle

# 态度模型
---
###态度模型

* **裁决依据：法官意识形态及价值判断**

* **核心强调：大法官对自己**政策偏好**的实现**

* **法律现实主义**
  * “法律是不断变化的，又司法创造的。”
  
  * 要求对法律进行经验性科学研究

* **行为主义**  

  * 《罗斯福法院》(C.Herman.Pritchett)

* **心理学**  （Glendon Schubert） 

  * 案件和法官的价值取向都可以从意识形态的角度加以量化

* **经济学**
  
  * （ David Rohde；Harold Spaeth）
  
  * 裁决与具体的目的、规则、环境有关
  
---
### 从态度模型到理性选择模型

* 解释行为者关系：均衡关系

* 政策偏好 vs 任何目标

* 如何作出裁决的实质内容

---
class: inverse, center, middle

# 理性选择模型
---
### 理性选择模型

将经济学方法应用于政治行为和社会行为研究中

* 根据**个人偏好**和**现实情况**，**理性**选择「利益最大化」的行为

  * 预设一：大法官是有个人偏好的——与态度模型一致
  
  * 预设二：大法官会（也能）考虑现实情况（内部权力与外部权力）
  
  * 预设三：大法官会试图**寻找均衡**
  
---
### 最高法院和理性选择理论

#### 内部权力：最高法院内部的，各个法官之间的相互作用

* 与早期态度模型理论重合

* 无法直接验证均衡预测

****

#### 外部权力：其他政治行动者对最高法施加的各种约束

* 马科斯（Brain Marks）的分权模型

  * 最高法院需要**考虑**（甚至**遵从**）立法者的主流意见，避免自己的裁决被国会推翻
  
  * 在避免被国会推翻的前提下，尽量接近自己的理想点
  
---
### 分权模型的假定（与问题）

.pull-left[
**关于最高法院**

* 信息全透明

* 法律无弹性

  * 分权模型低估法院裁量的**自由度**

* 事件全独立

  * 忽视了最高法的**议题多元化**手段
]
  
.pull-right[
**关于国会**

* 立法过程零成本

* 否决无成本
]

****

**关于最高法院与国会的互动**

* 默认国会拥有最终否决权

* 假定大法官的偏好是外生的

---
### 理性选择模型

* 内部权力：研究缺失

* 外部权力（与其他政治行动者的关系）

  * **在避免被国会推翻的前提下，尽量接近自己的理想点**

  * 高估了理性裁决的可能性
  
      * 信息缺失
  
  * 低估了最高法的自由裁量权
  
      * 解释法律
      
      * 议题多元化
      
      * 国会的否决成本、立法成本
      
      * 违宪审查
  
  * 忽视了最高法和国会之间可能存在的内生互动关系
  
---
class: inverse, center, middle

# 模型检验

## 态度模型与理性选择模型
---
### 模型检验：态度模型

**检验指标：事实、态度以及其交互关系**

事实：搜查扣押事件

* 最高法裁决结果～下级法院案卷记录

  * 正当性基础、搜查对象、搜查范围、例外情况
  
* **事实问题将影响最高法院的裁决**

****

态度：外生测量系统--相关报纸对大法官的社论报道

**大法官的意识形态态度和其投票之间的关联性为0.76，*Adjusted* $R^2$=0.55**

* 检验发现，法律规定不是lurking variable

****
裁决～事实+态度

* 裁决～态度：预测正确率=70%

* 裁决～态度+事实：预测正确率=71%

---
###模型检验：分权模型

* 定性分析：循环论证问题、counter-facts

* 定量分析

  * 缺乏支持依据
  
---
class: inverse, center, middle

#谢谢大家！



  





